import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { MongoClient, ServerApiVersion } from "mongodb";
import { Button, Col, Row } from "antd";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Row>
                    <Col span={8}>8 Cột</Col>

                    <Col span={12}>12 Cột</Col>

                    <Col span={4}>4 Cột</Col>
                </Row>
            </main>
        </>
    );
}

// Chỉ chạy ở phía server
export const getServerSideProps = async ({ req, res, query }) => {
    const uri =
        "mongodb+srv://admin:oAvTr4r0j5ITvxBN@personal.ct8sdia.mongodb.net/?retryWrites=true&w=majority";
    const client = new MongoClient(uri, {
        useNewUrlParser: true,
        useUnifiedTopology: true,
        serverApi: ServerApiVersion.v1,
    });
    const connection = await client.connect();
    const db = connection.db("survey");
    const survey = db.collection("questions");

    const questions = survey.find(
        {},
        {
            projection: { _id: 0, title: 1 },
        }
    );
    const data = await questions.toArray();

    return {
        props: {
            data,
        },
    };
};
